const edit = true;

import BaseConfig from "./BaseConfig";
import { utiller as Util, exceptioner as ERROR, pooller as InfinitePool } from "utiller";
import _ from "lodash";
import libpath from "path";

class Config extends BaseConfig {
    /** -------------------- fields -------------------- **/

    /** -------------------- functions -------------------- **/

    constructor(props) {
        super(props);
    }
    cities = [
        { value: "1", label: "台北市" },
        { value: "2", label: "新北市" },
        { value: "3", label: "桃園市" },
        { value: "4", label: "台中市" },
        { value: "5", label: "台南市" },
        { value: "6", label: "高雄市" },
        { value: "7", label: "基隆市" },
        { value: "8", label: "新竹市" },
        { value: "9", label: "嘉義市" },
        { value: "10", label: "新竹縣" },
        { value: "11", label: "苗栗縣" },
        { value: "12", label: "彰化縣" },
        { value: "13", label: "南投縣" },
        { value: "14", label: "雲林縣" },
        { value: "15", label: "嘉義縣" },
        { value: "16", label: "屏東縣" },
        { value: "17", label: "宜蘭縣" },
        { value: "18", label: "花蓮縣" },
        { value: "19", label: "台東縣" }
    ];

    districts = [
        // 台北市
        { value: "1", label: "中正區", type: 1 },
        { value: "2", label: "大同區", type: 1 },
        { value: "3", label: "中山區", type: 1 },
        { value: "4", label: "松山區", type: 1 },
        { value: "5", label: "大安區", type: 1 },
        { value: "6", label: "萬華區", type: 1 },
        { value: "7", label: "信義區", type: 1 },
        { value: "8", label: "士林區", type: 1 },
        { value: "9", label: "北投區", type: 1 },
        { value: "10", label: "內湖區", type: 1 },
        { value: "11", label: "南港區", type: 1 },
        { value: "12", label: "文山區", type: 1 },
        // 新北市
        { value: "13", label: "板橋區", type: 2 },
        { value: "14", label: "三重區", type: 2 },
        { value: "15", label: "中和區", type: 2 },
        { value: "16", label: "永和區", type: 2 },
        { value: "17", label: "新莊區", type: 2 },
        { value: "18", label: "新店區", type: 2 },
        { value: "19", label: "樹林區", type: 2 },
        { value: "20", label: "鶯歌區", type: 2 },
        { value: "21", label: "三峽區", type: 2 },
        { value: "22", label: "淡水區", type: 2 },
        { value: "23", label: "汐止區", type: 2 },
        { value: "24", label: "瑞芳區", type: 2 },
        { value: "25", label: "土城區", type: 2 },
        { value: "26", label: "蘆洲區", type: 2 },
        { value: "27", label: "五股區", type: 2 },
        { value: "28", label: "泰山區", type: 2 },
        { value: "29", label: "林口區", type: 2 },
        { value: "30", label: "深坑區", type: 2 },
        { value: "31", label: "石碇區", type: 2 },
        { value: "32", label: "坪林區", type: 2 },
        { value: "33", label: "三芝區", type: 2 },
        { value: "34", label: "石門區", type: 2 },
        { value: "35", label: "八里區", type: 2 },
        { value: "36", label: "平溪區", type: 2 },
        { value: "37", label: "雙溪區", type: 2 },
        { value: "38", label: "貢寮區", type: 2 },

        // 桃園市
        { value: "39", label: "桃園區", type: 3 },
        { value: "40", label: "中壢區", type: 3 },
        { value: "41", label: "平鎮區", type: 3 },
        { value: "42", label: "八德區", type: 3 },
        { value: "43", label: "楊梅區", type: 3 },
        { value: "44", label: "蘆竹區", type: 3 },
        { value: "45", label: "大溪區", type: 3 },
        { value: "46", label: "龜山區", type: 3 },
        { value: "47", label: "龍潭區", type: 3 },
        { value: "48", label: "新屋區", type: 3 },
        { value: "49", label: "觀音區", type: 3 },
        { value: "50", label: "復興區", type: 3 },

        { value: "51", label: "中區", type: 4 },
        { value: "52", label: "東區", type: 4 },
        { value: "53", label: "南區", type: 4 },
        { value: "54", label: "西區", type: 4 },
        { value: "55", label: "北區", type: 4 },
        { value: "56", label: "西屯區", type: 4 },
        { value: "57", label: "南屯區", type: 4 },
        { value: "58", label: "北屯區", type: 4 },
        { value: "59", label: "豐原區", type: 4 },
        { value: "60", label: "東勢區", type: 4 },
        { value: "61", label: "大甲區", type: 4 },
        { value: "62", label: "清水區", type: 4 },
        { value: "63", label: "沙鹿區", type: 4 },
        { value: "64", label: "梧棲區", type: 4 },
        { value: "65", label: "后里區", type: 4 },
        { value: "66", label: "神岡區", type: 4 },
        { value: "67", label: "潭子區", type: 4 },
        { value: "68", label: "大雅區", type: 4 },
        { value: "69", label: "新社區", type: 4 },
        { value: "70", label: "石岡區", type: 4 },
        { value: "71", label: "外埔區", type: 4 },
        { value: "72", label: "大安區", type: 4 },
        { value: "73", label: "烏日區", type: 4 },
        { value: "74", label: "大肚區", type: 4 },
        { value: "75", label: "龍井區", type: 4 },
        { value: "76", label: "霧峰區", type: 4 },
        { value: "77", label: "太平區", type: 4 },
        { value: "78", label: "大里區", type: 4 },
        { value: "79", label: "和平區", type: 4 },

        { value: "80", label: "中西區", type: 5 },
        { value: "81", label: "東區", type: 5 },
        { value: "82", label: "南區", type: 5 },
        { value: "83", label: "北區", type: 5 },
        { value: "84", label: "安平區", type: 5 },
        { value: "85", label: "安南區", type: 5 },
        { value: "86", label: "永康區", type: 5 },
        { value: "87", label: "歸仁區", type: 5 },
        { value: "88", label: "新化區", type: 5 },
        { value: "89", label: "左鎮區", type: 5 },
        { value: "90", label: "玉井區", type: 5 },
        { value: "91", label: "楠西區", type: 5 },
        { value: "92", label: "南化區", type: 5 },
        { value: "93", label: "仁德區", type: 5 },
        { value: "94", label: "關廟區", type: 5 },
        { value: "95", label: "龍崎區", type: 5 },
        { value: "96", label: "官田區", type: 5 },
        { value: "97", label: "麻豆區", type: 5 },
        { value: "98", label: "佳里區", type: 5 },
        { value: "99", label: "西港區", type: 5 },
        { value: "100", label: "七股區", type: 5 },
        { value: "101", label: "將軍區", type: 5 },
        { value: "102", label: "學甲區", type: 5 },
        { value: "103", label: "北門區", type: 5 },
        { value: "104", label: "新營區", type: 5 },
        { value: "105", label: "後壁區", type: 5 },
        { value: "106", label: "白河區", type: 5 },
        { value: "107", label: "東山區", type: 5 },
        { value: "108", label: "六甲區", type: 5 },
        { value: "109", label: "下營區", type: 5 },
        { value: "110", label: "柳營區", type: 5 },
        { value: "111", label: "鹽水區", type: 5 },
        { value: "112", label: "善化區", type: 5 },
        { value: "113", label: "大內區", type: 5 },
        { value: "114", label: "山上區", type: 5 },
        { value: "115", label: "新市區", type: 5 },
        { value: "116", label: "安定區", type: 5 },

        { value: "117", label: "楠梓區", type: 6 },
        { value: "118", label: "左營區", type: 6 },
        { value: "119", label: "鼓山區", type: 6 },
        { value: "120", label: "三民區", type: 6 },
        { value: "121", label: "新興區", type: 6 },
        { value: "122", label: "苓雅區", type: 6 },
        { value: "123", label: "前金區", type: 6 },
        { value: "124", label: "前鎮區", type: 6 },
        { value: "125", label: "旗津區", type: 6 },
        { value: "126", label: "小港區", type: 6 },
        { value: "127", label: "鳳山區", type: 6 },
        { value: "128", label: "林園區", type: 6 },
        { value: "129", label: "大寮區", type: 6 },
        { value: "130", label: "大樹區", type: 6 },
        { value: "131", label: "大社區", type: 6 },
        { value: "132", label: "仁武區", type: 6 },
        { value: "133", label: "鳥松區", type: 6 },
        { value: "134", label: "岡山區", type: 6 },
        { value: "135", label: "橋頭區", type: 6 },
        { value: "136", label: "燕巢區", type: 6 },
        { value: "137", label: "田寮區", type: 6 },
        { value: "138", label: "阿蓮區", type: 6 },
        { value: "139", label: "路竹區", type: 6 },
        { value: "140", label: "湖內區", type: 6 },
        { value: "141", label: "茄萣區", type: 6 },
        { value: "142", label: "永安區", type: 6 },
        { value: "143", label: "彌陀區", type: 6 },
        { value: "144", label: "梓官區", type: 6 },
        { value: "145", label: "旗山區", type: 6 },
        { value: "146", label: "美濃區", type: 6 },
        { value: "147", label: "六龜區", type: 6 },
        { value: "148", label: "甲仙區", type: 6 },
        { value: "149", label: "杉林區", type: 6 },
        { value: "150", label: "內門區", type: 6 },
        { value: "151", label: "茂林區", type: 6 },
        { value: "152", label: "桃源區", type: 6 },
        { value: "153", label: "那瑪夏區", type: 6 },
        { value: "154", label: "仁愛區", type: 7 },
        { value: "155", label: "信義區", type: 7 },
        { value: "156", label: "中正區", type: 7 },
        { value: "157", label: "中山區", type: 7 },
        { value: "158", label: "安樂區", type: 7 },
        { value: "159", label: "暖暖區", type: 7 },
        { value: "160", label: "七堵區", type: 7 },
        { value: "161", label: "東區", type: 8 },
        { value: "162", label: "北區", type: 8 },
        { value: "163", label: "香山區", type: 8 },
        { value: "164", label: "東區", type: 9 },
        { value: "165", label: "西區", type: 9 },
        { value: "166", label: "竹北市", type: 10 },
        { value: "167", label: "竹東鎮", type: 10 },
        { value: "168", label: "新埔鎮", type: 10 },
        { value: "169", label: "關西鎮", type: 10 },
        { value: "170", label: "湖口鄉", type: 10 },
        { value: "171", label: "新豐鄉", type: 10 },
        { value: "172", label: "芎林鄉", type: 10 },
        { value: "173", label: "橫山鄉", type: 10 },
        { value: "174", label: "北埔鄉", type: 10 },
        { value: "175", label: "寶山鄉", type: 10 },
        { value: "176", label: "峨眉鄉", type: 10 },
        { value: "177", label: "尖石鄉", type: 10 },
        { value: "178", label: "五峰鄉", type: 10 },
        { value: "179", label: "苗栗市", type: 11 },
        { value: "180", label: "頭份市", type: 11 },
        { value: "181", label: "竹南鎮", type: 11 },
        { value: "182", label: "後龍鎮", type: 11 },
        { value: "183", label: "通霄鎮", type: 11 },
        { value: "184", label: "苑裡鎮", type: 11 },
        { value: "185", label: "卓蘭鎮", type: 11 },
        { value: "186", label: "造橋鄉", type: 11 },
        { value: "187", label: "三灣鄉", type: 11 },
        { value: "188", label: "南庄鄉", type: 11 },
        { value: "189", label: "大湖鄉", type: 11 },
        { value: "190", label: "泰安鄉", type: 11 },
        { value: "191", label: "銅鑼鄉", type: 11 },
        { value: "192", label: "三義鄉", type: 11 },
        { value: "193", label: "西湖鄉", type: 11 },
        { value: "194", label: "頭屋鄉", type: 11 },
        { value: "195", label: "彰化市", type: 12 },
        { value: "196", label: "鹿港鎮", type: 12 },
        { value: "197", label: "和美鎮", type: 12 },
        { value: "198", label: "員林市", type: 12 },
        { value: "199", label: "溪湖鎮", type: 12 },
        { value: "200", label: "田中鎮", type: 12 },
        { value: "201", label: "北斗鎮", type: 12 },
        { value: "202", label: "二林鎮", type: 12 },
        { value: "203", label: "南投鎮", type: 12 },
        { value: "204", label: "福興鄉", type: 12 },
        { value: "205", label: "秀水鄉", type: 12 },
        { value: "206", label: "花壇鄉", type: 12 },
        { value: "207", label: "芬園鄉", type: 12 },
        { value: "208", label: "大村鄉", type: 12 },
        { value: "209", label: "埔鹽鄉", type: 12 },
        { value: "210", label: "埔心鄉", type: 12 },
        { value: "211", label: "永靖鄉", type: 12 },
        { value: "212", label: "社頭鄉", type: 12 },
        { value: "213", label: "二水鄉", type: 12 },
        { value: "214", label: "田尾鄉", type: 12 },
        { value: "215", label: "埤頭鄉", type: 12 },
        { value: "216", label: "溪州鄉", type: 12 },
        { value: "217", label: "斗六市", type: 13 },
        { value: "218", label: "斗南鎮", type: 13 },
        { value: "219", label: "虎尾鎮", type: 13 },
        { value: "220", label: "西螺鎮", type: 13 },
        { value: "221", label: "土庫鎮", type: 13 },
        { value: "222", label: "北港鎮", type: 13 },
        { value: "223", label: "古坑鄉", type: 13 },
        { value: "224", label: "大埤鄉", type: 13 },
        { value: "225", label: "莿桐鄉", type: 13 },
        { value: "226", label: "林內鄉", type: 13 },
        { value: "227", label: "二崙鄉", type: 13 },
        { value: "228", label: "崙背鄉", type: 13 },
        { value: "229", label: "麥寮鄉", type: 13 },
        { value: "230", label: "東勢鄉", type: 13 },
        { value: "231", label: "褒忠鄉", type: 13 },
        { value: "232", label: "臺西鄉", type: 13 },
        { value: "233", label: "元長鄉", type: 13 },
        { value: "234", label: "四湖鄉", type: 13 },
        { value: "235", label: "口湖鄉", type: 13 },
        { value: "236", label: "水林鄉", type: 13 },
        { value: "237", label: "太保市", type: 14 },
        { value: "238", label: "朴子市", type: 14 },
        { value: "239", label: "布袋鎮", type: 14 },
        { value: "240", label: "大林鎮", type: 14 },
        { value: "241", label: "民雄鄉", type: 14 },
        { value: "242", label: "溪口鄉", type: 14 },
        { value: "243", label: "新港鄉", type: 14 },
        { value: "244", label: "六腳鄉", type: 14 },
        { value: "245", label: "東石鄉", type: 14 },
        { value: "246", label: "義竹鄉", type: 14 },
        { value: "247", label: "鹿草鄉", type: 14 },
        { value: "248", label: "水上鄉", type: 14 },
        { value: "249", label: "中埔鄉", type: 14 },
        { value: "250", label: "竹崎鄉", type: 14 },
        { value: "251", label: "梅山鄉", type: 14 },
        { value: "252", label: "番路鄉", type: 14 },
        { value: "253", label: "大埔鄉", type: 14 },
        { value: "254", label: "阿里山鄉", type: 14 },
        { value: "255", label: "屏東市", type: 15 },
        { value: "256", label: "潮州鎮", type: 15 },
        { value: "257", label: "東港鎮", type: 15 },
        { value: "258", label: "恆春鎮", type: 15 },
        { value: "259", label: "萬丹鄉", type: 15 },
        { value: "260", label: "長治鄉", type: 15 },
        { value: "261", label: "麟洛鄉", type: 15 },
        { value: "262", label: "九如鄉", type: 15 },
        { value: "263", label: "里港鄉", type: 15 },
        { value: "264", label: "鹽埔鄉", type: 15 },
        { value: "265", label: "高樹鄉", type: 15 },
        { value: "266", label: "萬巒鄉", type: 15 },
        { value: "267", label: "內埔鄉", type: 15 },
        { value: "268", label: "竹田鄉", type: 15 },
        { value: "269", label: "新埤鄉", type: 15 },
        { value: "270", label: "枋寮鄉", type: 15 },
        { value: "271", label: "枋山鄉", type: 15 },
        { value: "272", label: "春日鄉", type: 15 },
        { value: "273", label: "獅子鄉", type: 15 },
        { value: "274", label: "車城鄉", type: 15 },
        { value: "275", label: "牡丹鄉", type: 15 },
        { value: "276", label: "三地門鄉", type: 15 },
        { value: "277", label: "霧臺鄉", type: 15 },
        { value: "278", label: "瑪家鄉", type: 15 },
        { value: "279", label: "泰武鄉", type: 15 },
        { value: "280", label: "來義鄉", type: 15 },
        { value: "281", label: "春日鄉", type: 15 },
        { value: "282", label: "獅子鄉", type: 15 },
        { value: "283", label: "牡丹鄉", type: 15 },
        { value: "284", label: "宜蘭市", type: 16 },
        { value: "285", label: "羅東鎮", type: 16 },
        { value: "286", label: "蘇澳鎮", type: 16 },
        { value: "287", label: "頭城鎮", type: 16 },
        { value: "288", label: "礁溪鄉", type: 16 },
        { value: "289", label: "壯圍鄉", type: 16 },
        { value: "290", label: "員山鄉", type: 16 },
        { value: "291", label: "冬山鄉", type: 16 },
        { value: "292", label: "五結鄉", type: 16 },
        { value: "293", label: "三星鄉", type: 16 },
        { value: "294", label: "大同鄉", type: 16 },
        { value: "295", label: "南澳鄉", type: 16 }
    ];

    getDistrictsByCity(valueOfCity) {
        return _.filter(this.districts, (each) => _.isEqual(each.type, valueOfCity));
    }
    /** -------------------- async api -------------------- **/
}

export default new Config();
